name: Patcher

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  do-not-merge:
    name: Check for README-TO-COMPLETE-UPDATE.md files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "**/README-TO-COMPLETE-UPDATE.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo "This pull request contains `README-TO-COMPLETE-UPDATE.md` files"
          echo "Check for outstanding `README-TO-COMPLETE-UPDATE.md` files"
          echo "This check will pass, when all the outstanding files have been actioned and deleted"
          exit 1
