name: Update Dev Dependencies
on:
  workflow_dispatch:
  repository_dispatch:
    types: [new_module_release]
  schedule:
    # 04:15 UTC on Mondays
    - cron: '15 4 * * 1'
  pull_request_target:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

env:
  ENV_FOLDER_NAME: dev

jobs:
  trigger-next-env:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'updates-dev')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ github.repository }}
          event-type: dev_updates_merged
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "branch": "${{ github.head_ref }}" }'
  patcher-report:
    if: github.event_name == 'repository_dispatch' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      dependencies: ${{ steps.get-dependencies.outputs.dependencies }}
    steps:
      - uses: actions/checkout@v3
      - uses: gruntwork-io/patcher-action@v1
        id: get-dependencies
        with:
          patcher_command: report
          working_dir: ${{ env.ENV_FOLDER_NAME }}

  update-env:
    needs: [patcher-report]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency: ${{ fromJson(needs.patcher-report.outputs.dependencies) }}
    steps:
      - uses: actions/checkout@v3
      - name: Create trigger source message
        if: github.event_name == 'repository_dispatch'
        id: trigger_event
        run: |
          echo "source=Triggered by a new release in \`dogfood-infrastructure-modules\`" >> "$GITHUB_OUTPUT"
      - uses: gruntwork-io/patcher-action@v1
        with:
          working_dir: ${{ env.ENV_FOLDER_NAME }}
          dependency: ${{ matrix.dependency }}
