name: Update Prod Dependencies

on:
  workflow_dispatch:
  repository_dispatch:
    types: [stage_updates_merged]

permissions:
  contents: write

env:
  ENV_FOLDER_NAME: prod

jobs:
  update-env:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gruntwork-io/patcher-action@v1
        with:
          working_dir: ${{ env.ENV_FOLDER_NAME }}
