name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn lint

  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn
      - name: Rebuild the dist/ directory
        run: yarn build
      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi

  # TODO - upload file
  patcher-report:
    runs-on: ubuntu-latest
    outputs:
      dependencies: ${{ steps.run-report.outputs.dependencies }}
    steps:
      - uses: actions/checkout@v4
      - name: Patcher
        id: run-report
        uses: ./
        with:
          patcher_command: report
          working_dir: infrastructure-live
